### ISSUE TITLE
Analysis TOML file requires "codebase" section

### ISSUE THREAD

**Issue by Pennycook** [intel/code-base-investigator#71]
### Expected behavior

The following analysis file should be valid:
```toml
[platform.cpu]
commands = "cpu.json"

[platform.gpu]
commands = "gpu.json"
```

### Actual behavior

We currently assume that the "codebase" section is always present:
```sh
[ERROR   ] 'codebase'
```

### Steps to reproduce the problem

Running `codebasin` with the analysis file shown above will produce the error.  Adding an empty "codebase" section causes things to work as expected.

### Specifications

Tested with 9bfd0fbadf0a29af4e587b5c5ddf8b28bc0a286b.
